### ISSUE TITLE
Preview link - hover is not working.

### ISSUE THREAD

**Issue by shiv-chan** [shiv-chan/old-portfolio#1]
https://github.com/shiv-chan/Portfolio/blob/623b940912de6bb0a2761619c8d5e4bbccc788b1/CSS/_components.scss#L306-L317
The preview links on the back of the project cards should have a hover effect, but it doesn't work although the GitHub links work properly.

*Seems not like it has to do with `z-index`.

**Comment by shiv-chan** [comment]
https://github.com/shiv-chan/Portfolio/blob/0765b46b745a8077535ce792903b5da34ddba1aa/CSS/_components.scss#L260-L265
Change height to `70px` from `100%` to fix.

**Comment by raphaelAndrade** [comment]
Hi @shiv-chan how are you?
You can close the issue once we already fixed that. I am really happy that you starting to use GitHub Issues. I am really with your progress. :)
